services:
  _defaults:
    public: true
    autowire: true

  HeimrichHannot\BackendLostPasswordBundle\Controller\BackendController: ~
  HeimrichHannot\BackendLostPasswordBundle\Manager\BackendLostPasswordManager: ~